# ruby encoding: utf-8
sql = <<END
	INSERT INTO users (username, email, passwd, date_sign_up, is_admin) VALUES
		('Boris', 'boris@welp.com', crypt('welp', gen_salt('bf',8)), '1/01/1970', TRUE),
		('Fred', 'fred@welp.com', crypt('welp', gen_salt('bf',8)), '1/01/1970', TRUE),
		('Brenda', 'brenda@welp.com', crypt('welp', gen_salt('bf',8)), '1/01/1970', FALSE),
		('Ivan', 'ivan@welp.com', crypt('welp', gen_salt('bf',8)), '1/01/1970', FALSE),
		('Joelle', 'joelle@welp.com', crypt('welp', gen_salt('bf',8)), '1/01/1970', FALSE),
		('Serge', 'serge@welp.com', crypt('welp', gen_salt('bf',8)), '1/01/1970', FALSE),
		('Sarah', 'sarah@welp.com', crypt('welp', gen_salt('bf',8)), '1/01/1970', FALSE);
	INSERT INTO places (creator_id, creation_date, name, street, num, zip, city, longitude, latitude, phone, website, kind) VALUES
		((SELECT user_id FROM users WHERE username = 'Boris'), '1/03/2008', 'Ratabar', 'Chaussée de Boondael', '345', '1050', 'Ixelles', '4.384074', '50.818606', '02/644 09 92', 'NULL', 'cafe'),
		((SELECT user_id FROM users WHERE username = 'Boris'), '2/01/2008', 'Waff', 'Chaussée de Boondael', '455', '1050', 'Ixelles', '4.389335', '50.816415', '02/640 00 42', 'http://www.waff.be', 'cafe'),
		((SELECT user_id FROM users WHERE username = 'Boris'), '02/01/2008', 'Tavernier', 'Chaussée de Boondael', '44', '1050', 'Ixelles', '4.389117', '50.816702', '02/640 71 91', 'www.le-tavernier.be', 'cafe'),
		((SELECT user_id FROM users WHERE username = 'Boris'), '23/03/2008', 'Belga', 'Place Eugène Flagey', '18', '1050', 'Ixelles', '4.372582', '50.827164', '02/640 35 08', 'www.cafebelga.be', 'cafe'),
		((SELECT user_id FROM users WHERE username = 'Boris'), '6/12/2007', 'Marché au vin', 'Rue du Belvédère', '14', '1050', 'Ixelles', '4.374044', '50.826765', '02/640 56 10', 'NULL', 'cafe'),
		((SELECT user_id FROM users WHERE username = 'Fred'), '3/03/2008', 'Delecta', 'Rue lannoy', '2', '1050', 'Ixelles', '4.369927', '50.825975', '02/644 19 49', 'NULL', 'cafe'),
		((SELECT user_id FROM users WHERE username = 'Fred'), '24/01/2008', 'Piola', 'Rue du page', '2', '1050', 'Ixelles', '4.359633', '50.824129', '02/538 91 29', 'NULL', 'cafe'),
		((SELECT user_id FROM users WHERE username = 'Fred'), '2/03/2008', 'Pantin', 'Chaussée d''ixelles', '355', '1050', 'Ixelles', '4.371326', '50.827992', '02/644 80 91', 'NULL', 'cafe'),
		((SELECT user_id FROM users WHERE username = 'Fred'), '1/08/2008', 'Gauguin', 'Chaussée de Boondael', '420', '1050', 'Ixelles', '4.388552', '50.817414', '02/646 39 72', 'NULL', 'cafe'),
		((SELECT user_id FROM users WHERE username = 'Boris'), '2/10/2008', 'Le Corto', 'Chaussée de Boondael', '485', '1050', 'Ixelles', '4.390143', '50.815315', '02/000 00 00', 'NULL', 'cafe'),
		((SELECT user_id FROM users WHERE username = 'Boris'), '2/04/2008', 'Suprabailly', 'Rue du bailli', '77', '1050', 'Ixelles', '4.360097', '50.825774', '02/534 09 01', 'NULL', 'cafe'),
		((SELECT user_id FROM users WHERE username = 'Boris'), '4/04/2003', 'SuperMercado', 'Rue de Florence', '100', '1050', 'Ixelles', '4.36018', '50.8296', '02/222 22 22', 'NULL', 'cafe'),
		((SELECT user_id FROM users WHERE username = 'Fred'), '2/09/2008', 'Brasserie L''union', 'Parvis de Saint-Gilles', '55', '1050', 'Ixelles', '4.346077', '50.830774', '02/538 15 79', 'NULL', 'cafe'),
		((SELECT user_id FROM users WHERE username = 'Fred'), '4/07/2004', 'Greenwich', 'Rue des Chartreux', '5', '1050', 'Ixelles', '4.347482', '50.848845', '02/511 41 67', 'NULL', 'cafe'),
		((SELECT user_id FROM users WHERE username = 'Fred'), '2/10/2008', 'Michael Collins', 'Rue du Bailli', '1', '1050', 'Ixelles', '4.363494', '50.827167', '02/644 61 21', 'NULL', 'cafe'),
		((SELECT user_id FROM users WHERE username = 'Fred'), '19/01/2008', 'de Valera''s', 'Place Flagey', '17', '1050', 'Ixelles', '4.371694', '50.827513', '02/649 80 54', 'NULL', 'cafe'),
		((SELECT user_id FROM users WHERE username = 'Boris'), '2/10/2008', 'Chez Théo Sodexho ULB', 'Avenue Paul Héger', '22', '1050', 'Ixelles', '4.381571', '50.813257', '02/650 49 35', 'http://wwwdev.ulb.ac.be/restaurants/solbosch_s/r_pub.php3', 'restaurant'),
		((SELECT user_id FROM users WHERE username = 'Boris'), '2/10/2008', 'Mirabelle', 'Chaussée de Boondael', '459', '1050', 'Ixelles', '4.389422', '50.8163', '02/649 51 73', 'NULL', 'restaurant'),
		((SELECT user_id FROM users WHERE username = 'Boris'), '2/10/2008', 'Mano a Mano', 'Rue Saint-Boniface', '8', '1050', 'Ixelles', '4.364806', '50.835827', '02/502 08 01', 'NULL', 'restaurant'),
		((SELECT user_id FROM users WHERE username = 'Boris'), '2/10/2008', 'Le belga queen', 'Rue Fossé-aux-Loups', '32', '1000', 'Bruxelles', '4.35448', '50.850287', '02/217 21 87', 'http://www.belgaqueen.be/', 'restaurant'),
		((SELECT user_id FROM users WHERE username = 'Boris'), '2/10/2008', 'Indochine', 'Rue Lesbroussart', '58', '1050', 'Ixelles', '4.36822', '50.827658', '02/649 96 15', 'NULL', 'restaurant'),
		((SELECT user_id FROM users WHERE username = 'Fred'), '2/10/2008', 'L''horloge du sud', 'Rue du Trône', '141', '1050', 'Ixelles', '4.371431', '50.835815', '02/512 18 64', 'NULL', 'restaurant'),
		((SELECT user_id FROM users WHERE username = 'Fred'), '2/10/2008', 'Grenier d''Elvire', 'Chaussée de Boondael', '339A', '1050', 'Ixelles', '4.38384', '50.818766', '02/648 43 48', 'http://www2.resto.be/grenierdelvire/', 'restaurant'),
		((SELECT user_id FROM users WHERE username = 'Fred'), '2/10/2008', 'Grain de sel', 'Chaussée de Vleurgat', '9', '1050', 'Ixelles', '4.371216', '50.827518', '02/648 18 58', 'NULL', 'restaurant'),
		((SELECT user_id FROM users WHERE username = 'Fred'), '2/10/2008', 'Le Fin de Siècle', 'rue des Chartreux', '10', '1000', 'Bruxelles', '4.347392', '50.848845', '02/648 80 81', 'http://www.lafindesiecle.be', 'restaurant'),
		((SELECT user_id FROM users WHERE username = 'Fred'), '2/10/2008', 'Comme Chez Soi', 'Place Rouppe', '23', '1000', 'Bruxelles', '4.345686', '50.842639', '02/512 29 21', 'www.commechezsoi.be', 'restaurant'),
		((SELECT user_id FROM users WHERE username = 'Boris'), '2/10/2008', 'Le café des épices', 'Place Jourdan', '21', '1040', 'Etterbeek', '4.381584', '50.837219', '02/280 43 17', 'www.cafedesepices.be', 'restaurant'),
		((SELECT user_id FROM users WHERE username = 'Boris'), '2/10/2008', 'Bécasse', 'Chaussée de Boondael', '476', '1050', 'Ixelles', '4.389766', '50.815858', '02/649 06 41', 'NULL', 'restaurant'),
		((SELECT user_id FROM users WHERE username = 'Boris'), '2/10/2008', 'La Bastoche', 'Chaussée de Boondael', '473', '1050', 'Ixelles', '4.389732', '50.815899', '02/640 34 17', 'NULL', 'restaurant'),
		((SELECT user_id FROM users WHERE username = 'Fred'), '2/10/2008', 'Au Vieux Bruxelles', 'Rue Saint-Boniface', '35', '1050', 'Ixelles', '4.363727', '50.836346', '02/503 31 11', 'NULL', 'restaurant');
	INSERT INTO cafes (place_id, smoking, snack) VALUES
		((SELECT place_id FROM places WHERE name = 'Ratabar'), 'true', 'false'),
		((SELECT place_id FROM places WHERE name = 'Waff'), 'true', 'true'),
		((SELECT place_id FROM places WHERE name = 'Tavernier'), 'false', 'true'),
		((SELECT place_id FROM places WHERE name = 'Belga'), 'false', 'true'),
		((SELECT place_id FROM places WHERE name = 'Marché au vin'), 'true', 'true'),
		((SELECT place_id FROM places WHERE name = 'Delecta'), 'false', 'true'),
		((SELECT place_id FROM places WHERE name = 'Piola'), 'false', 'true'),
		((SELECT place_id FROM places WHERE name = 'Pantin'), 'true', 'false'),
		((SELECT place_id FROM places WHERE name = 'Gauguin'), 'true', 'false'),
		((SELECT place_id FROM places WHERE name = 'Le Corto'), 'true', 'true'),
		((SELECT place_id FROM places WHERE name = 'Suprabailly'), 'true', 'true'),
		((SELECT place_id FROM places WHERE name = 'SuperMercado'), 'true', 'false'),
		((SELECT place_id FROM places WHERE name = 'Brasserie L''union'), 'true', 'true'),
		((SELECT place_id FROM places WHERE name = 'Greenwich'), 'true', 'true'),
		((SELECT place_id FROM places WHERE name = 'Michael Collins'), 'true', 'true'),
		((SELECT place_id FROM places WHERE name = 'de Valera''s'), 'true', 'true');
	INSERT INTO restaurants (place_id, price_range, banquet, take_out, delivery, closed) VALUES
		((SELECT place_id FROM places WHERE name = 'Chez Théo Sodexho ULB'), '6', '200', 'true', 'true', B'11010101010111'),
		((SELECT place_id FROM places WHERE name = 'Mirabelle'), '40', '40', 'false', 'false', B'00000000000000'),
		((SELECT place_id FROM places WHERE name = 'Mano a Mano'), '30', '10', 'true', 'true', B'11000000000010'),
		((SELECT place_id FROM places WHERE name = 'Le belga queen'), '50', '180', 'false', 'false', B'00000000000000'),
		((SELECT place_id FROM places WHERE name = 'Indochine'), '20', '30', 'true', 'true', B'11000000000000'),
		((SELECT place_id FROM places WHERE name = 'L''horloge du sud'), '30', '150', 'true', 'false', B'11000000000010'),
		((SELECT place_id FROM places WHERE name = 'Grenier d''Elvire'), '20', '25', 'true', 'true', B'11100000000010'),
		((SELECT place_id FROM places WHERE name = 'Grain de sel'), '30', '60', 'true', 'true', B'11110000000010'),
		((SELECT place_id FROM places WHERE name = 'Le Fin de Siècle'), '20', '10', 'false', 'false', B'00000000000000'),
		((SELECT place_id FROM places WHERE name = 'Comme Chez Soi'), '100', '34', 'false', 'false', B'11110010000000'),
		((SELECT place_id FROM places WHERE name = 'Le café des épices'), '40', '25', 'false', 'false', B'00000000000000'),
		((SELECT place_id FROM places WHERE name = 'Bécasse'), '40', '80', 'false', 'false', B'00000000000000'),
		((SELECT place_id FROM places WHERE name = 'La Bastoche'), '20', '20', 'false', 'false', B'00000000000000'),
		((SELECT place_id FROM places WHERE name = 'Au Vieux Bruxelles'), '40', '40', 'false', 'false', B'11110000000000');
	INSERT INTO comments (place_id, user_id, stars, text_comment, creation_date) VALUES
		((SELECT place_id FROM places WHERE name = 'Ratabar'), (SELECT user_id FROM users WHERE username = 'Boris'), '5', 'Bonne ambiance à partir de 23h. Déco apache. Spécialité : sous marin.', '2/05/2008'),
		((SELECT place_id FROM places WHERE name = 'Ratabar'), (SELECT user_id FROM users WHERE username = 'Brenda'), '3', 'Spécialité : sous marin. Petit défaut, il n''y a rien à manger mais on peut aller chercher un durum en face.', '7/08/2008'),
		((SELECT place_id FROM places WHERE name = 'Waff'), (SELECT user_id FROM users WHERE username = 'Ivan'), '4', 'Très enfumé mais superbe terrasse. Bons cocktails. Happy hour de 18 à 20h : deux cocktails pour le prix d''un. Serveurs parfois pas très sympas. Club privé avec sorteur à partir de 22h.', '2/03/2008'),
		((SELECT place_id FROM places WHERE name = 'Waff'), (SELECT user_id FROM users WHERE username = 'Brenda'), '2', 'Club privé avec sorteur à partir de 22h.', '1/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Waff'), (SELECT user_id FROM users WHERE username = 'Joelle'), '1', 'Serveurs parfois pas très sympas. Club privé avec sorteur à partir de 22h.', '5/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Tavernier'), (SELECT user_id FROM users WHERE username = 'Serge'), '4', 'Belle terrasse, ambiance un peu BCBG, concerts certains soirs. ', '2/05/2008'),
		((SELECT place_id FROM places WHERE name = 'Tavernier'), (SELECT user_id FROM users WHERE username = 'Joelle'), '2', 'Toilettes pas très propres.', '2/02/2008'),
		((SELECT place_id FROM places WHERE name = 'Belga'), (SELECT user_id FROM users WHERE username = 'Boris'), '3', 'Sympa à l''extérieur en été mais très bruyant à l''intérieur. ', '2/04/2008'),
		((SELECT place_id FROM places WHERE name = 'Marché au vin'), (SELECT user_id FROM users WHERE username = 'Ivan'), '5', 'Très bonne ambiance. Le patron connaît bien ses vins. Petit en cas offert avec le vin.', '2/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Marché au vin'), (SELECT user_id FROM users WHERE username = 'Boris'), '3', 'Un peu chèr.', '7/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Delecta'), (SELECT user_id FROM users WHERE username = 'Brenda'), '3', 'Bar classique. Terrasse sur le trottoir. Belle sélection de Tapas.', '3/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Delecta'), (SELECT user_id FROM users WHERE username = 'Boris'), '5', 'Belle sélection de Tapas.', '12/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Delecta'), (SELECT user_id FROM users WHERE username = 'Fred'), '4', 'Bon vin et tapas. Un peu cher.', '12/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Piola'), (SELECT user_id FROM users WHERE username = 'Sarah'), '1', 'Serveurs pas sympas. Carte ridicule.', '2/05/2008'),
		((SELECT place_id FROM places WHERE name = 'Piola'), (SELECT user_id FROM users WHERE username = 'Fred'), '2', 'Cher, tapas et vin pas mal.', '2/05/2008'),
		((SELECT place_id FROM places WHERE name = 'Pantin'), (SELECT user_id FROM users WHERE username = 'Ivan'), '5', 'Bar de gauchistes dont le patron s''appelle Jean-Marie.', '2/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Pantin'), (SELECT user_id FROM users WHERE username = 'Joelle'), '3', 'Très enfumé.', '9/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Pantin'), (SELECT user_id FROM users WHERE username = 'Fred'), '4', 'Sympaz, pas cher, jeu d''échec.', '9/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Gauguin'), (SELECT user_id FROM users WHERE username = 'Boris'), '3', 'Réservé uniquement aux étudiants.', '5/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Gauguin'), (SELECT user_id FROM users WHERE username = 'Serge'), '4', 'Ambiance festive.', '5/09/2008'),
		((SELECT place_id FROM places WHERE name = 'Gauguin'), (SELECT user_id FROM users WHERE username = 'Ivan'), '2', 'Très bruyant.', '1/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Gauguin'), (SELECT user_id FROM users WHERE username = 'Fred'), '2', 'Impossible d''avoir une bière après 20h, trop de monde.', '1/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Le Corto'), (SELECT user_id FROM users WHERE username = 'Boris'), '4', 'Minuscule bar mais très bonne ambiance. Prix très raisonnables et service à table. Le saucisson goute la nourriture pour chats. Cacahuètes gratuites. Terrasse sur la rue.', '2/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Suprabailly'), (SELECT user_id FROM users WHERE username = 'Brenda'), '3', 'Super ambiance !', '2/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Suprabailly'), (SELECT user_id FROM users WHERE username = 'Boris'), '4', ' Les habitués y viennent souvent entre amis et en soirée l’atmosphère y est à l’humour et à la bonne humeur !', '2/09/2008'),
		((SELECT place_id FROM places WHERE name = 'SuperMercado'), (SELECT user_id FROM users WHERE username = 'Ivan'), '4', 'Bar à cocktails très sympas - Quelques bon vins Espagnols', '2/10/2008'),
		((SELECT place_id FROM places WHERE name = 'SuperMercado'), (SELECT user_id FROM users WHERE username = 'Fred'), '4', 'Bonne adresse.', '2/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Brasserie L''union'), (SELECT user_id FROM users WHERE username = 'Serge'), '5', 'Un beau petit coin où il fait bon vivre, on s’y sent à la maison avec des bons petits plats et une ambiance multicolore... Le vrai visage de Bruxelles, qualité et ambiance! You wanna go where everybody knows your name…', '30/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Brasserie L''union'), (SELECT user_id FROM users WHERE username = 'Boris'), '5', 'Délicieux troquet, l''Union, avec sa faune toujours changeante et le plus souvent de bonne humeur. Les alcools à moins de 4 Euro y sont certainement pour quelque chose..', '05/09/2008'),
		((SELECT place_id FROM places WHERE name = 'Brasserie L''union'), (SELECT user_id FROM users WHERE username = 'Fred'), '5', 'Top.', '05/09/2008'),
		((SELECT place_id FROM places WHERE name = 'Greenwich'), (SELECT user_id FROM users WHERE username = 'Fred'), '4', 'bistrot tranquille, jeux d''échecs pour les passionnes, authentique', '5/06/2006'),
		((SELECT place_id FROM places WHERE name = 'Greenwich'), (SELECT user_id FROM users WHERE username = 'Ivan'), '1', '-35 ans s''abstenir', '2/10/2007'),
		((SELECT place_id FROM places WHERE name = 'Greenwich'), (SELECT user_id FROM users WHERE username = 'Serge'), '3', 'bon rapport qualité prix', '13/09/2008'),
		((SELECT place_id FROM places WHERE name = 'Michael Collins'), (SELECT user_id FROM users WHERE username = 'Sarah'), '3', 'Un pub traditionnel Irlandais dans Bruxelles avec comme activité principale la retransmission de match de foot ou de rugby. Bière à 4 euros et cocktails à 5 euros.', '4/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Michael Collins'), (SELECT user_id FROM users WHERE username = 'Brenda'), '3', 'Pub assez chèr', '3/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Michael Collins'), (SELECT user_id FROM users WHERE username = 'Fred'), '3', 'WiFi, quand ca marche. Hamburger++.', '3/10/2008'),
		((SELECT place_id FROM places WHERE name = 'de Valera''s'), (SELECT user_id FROM users WHERE username = 'Fred'), '3', 'Pub irlandais. Très bonne petite restauration surtout le Hamburger++.', '1/03/2008'),
		((SELECT place_id FROM places WHERE name = 'de Valera''s'), (SELECT user_id FROM users WHERE username = 'Sarah'), '4', 'Serveuses charmantes mais ne parlent pas français.', '9/02/2008'),
		((SELECT place_id FROM places WHERE name = 'de Valera''s'), (SELECT user_id FROM users WHERE username = 'Boris'), '1', 'Très plein les soirs de match, bruyant et enfumé.', '1/06/2008'),
		((SELECT place_id FROM places WHERE name = 'Chez Théo Sodexho ULB'), (SELECT user_id FROM users WHERE username = 'Serge'), '3', 'Bon steak le mercredi, ambiance retro "happy Days" très sympa! Beaucoup de monde en dehors des vacances, mais service impeccable! Surtout une serveuse blonde super souriante.
', '23/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Chez Théo Sodexho ULB'), (SELECT user_id FROM users WHERE username = 'Ivan'), '4', 'La sodexo, c''est différent! Vous êtes soucieux de votre santé, vous en avez assez du ''fast food'' et du sandwich ordinaire. Vous voulez quelque chose de différent. Vous avez raison. Chez Théo est un retaurant rapide de qualité, dont la devise est ''natrual, fresh and ready''.
', '2/11/2008'),
		((SELECT place_id FROM places WHERE name = 'Chez Théo Sodexho ULB'), (SELECT user_id FROM users WHERE username = 'Joelle'), '1', 'Faut pas déconner. Cher, pas bon même les choses les plus simples.', '29/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Chez Théo Sodexho ULB'), (SELECT user_id FROM users WHERE username = 'Fred'), '2', 'Testez absolument les nouvelles lasagnes (aubergine) et canneloni au rayon ''pates'', c''est bon. Si, si, c''est bon!', '3/11/2008'),
		((SELECT place_id FROM places WHERE name = 'Mirabelle'), (SELECT user_id FROM users WHERE username = 'Serge'), '5', 'Je suis un habitué de La Mirabelle, j''y ai mangé pour la première fois en 1983 (découverte de la brochette Macao qui n''est plus à la carte il me semble?) et depuis j''y retourne régulièrement, et j''apprécie beaucoup l''accueil sympa, le service rapide, et la bonne cuisine de type "brasserie", ingrédients frais et de qualité. Bien sûr le week-end en soirée ça peut être bondé et il vaudra mieux réserver, surtout pour les groupes. Samedi dernier nous avons goûté le gaspacho en suggestion et les fondus parmesan (avec le persil frit, chouette) et comme plat un waterzooï à la gantoise (copieux!) et un saumon poêlé aux légumes wok, avec 1/2 bouteille de vin. Tout était franchement très bon.
', '21/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Mirabelle'), (SELECT user_id FROM users WHERE username = 'Joelle'), '3', 'Loin d''être aussi parfait que ce que l''on dit : une table mal située (face aux toilettes) alors que d''autres tables sont restées vides . Service un peu rapide et pas très souriant. Nourriture correcte. Peut-être avions-nous choisi un mauvais jour ( il pleuvait!!). 
', '24/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Mirabelle'), (SELECT user_id FROM users WHERE username = 'Ivan'), '4', 'service toujours souriant et efficace, et qualité constante depuis.... ouh la la tant d''années !
', '2/11/2008'),
		((SELECT place_id FROM places WHERE name = 'Mano a Mano'), (SELECT user_id FROM users WHERE username = 'Fred'), '4', 'Resto cool et sympa où la nourriture est de qualité mais il ce n''est en rien un lieu calme et intime. ', '25/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Mano a Mano'), (SELECT user_id FROM users WHERE username = 'Sarah'), '4', ' Qualité du service parfois déçevante mais surtout dû au fait que le lieu est très fréquenté.', '28/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Mano a Mano'), (SELECT user_id FROM users WHERE username = 'Ivan'), '5', ' ça déchire. L''italie en plein. J''adore.', '28/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Le belga queen'), (SELECT user_id FROM users WHERE username = 'Joelle'), '5', 'Pour la seconde fois en qlq mois j''ai pu apprécié la fraicheur des produits du comptoir à huitre. Bonne présentation du plateau de fruit de mer à 60 euros /2 personnes, avec un sympathique sauvignon chilien...tout bien sauf peut être le service un peu expéditif, genre la vidange d''asssiette se fait sans nous en demandé l''autorisation..résultat pff j''avais plus d''aiguille pour mes bigorneaux ...mais bon ... (163488)
', '30/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Le belga queen'), (SELECT user_id FROM users WHERE username = 'Sarah'), '1', 'That''s really incredible! Such a beautiful place and such a bad service ! As usual you think you can have your dinner at 8:30PM and enjoy a nice evening ? Well not here they absolutely want to make a lot of money so you need to be there or at 7:00PM or at 9:30PM and they tell you they''ll throw you out if you are not finished! I only knew this in a few restaurants of London and by the time they realized that this helps loosing the local customers, it''s too late the place is already in bankrupcy. So watch out Belga Queen team and try to behave in front of your customer, your going to need them sometime... And food is so and so, so you are really going to need them ! ', '4/11/2008'),
		((SELECT place_id FROM places WHERE name = 'Le belga queen'), (SELECT user_id FROM users WHERE username = 'Joelle'), '4', 'J''y suis allée pour un lunch à deux personnes. La formule Business Lunch est avantageuse et nous avons très bien mangé. A recommander !
', '3/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Le belga queen'), (SELECT user_id FROM users WHERE username = 'Ivan'), '4', 'cadre superbe, bonne cuisine mais cher.', '2/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Le belga queen'), (SELECT user_id FROM users WHERE username = 'Serge'), '4', 'très bon', '2/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Le belga queen'), (SELECT user_id FROM users WHERE username = 'Brenda'), '4', 'Based in the premises of an old bank this is must visit restaurants in Brussels although its really a flashy brasserie. Dine in magnificent surroundings either at the oyster bar, beer bar or the brasserie itself where some mouth watering Belgian dishes are offered. Wine list is also extensive and will meet all tastes / budgets. Business lunch at €15 per head is fantastic value for money and worth checking out. Book in advance for weekends and evenings. Cigar lounge / club in basement finishes off an evening in style. I''m no guru but would give Belga a big thumbs up for anyone looking for a sophisticated yet charming dining experience in Brussels.', '2/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Indochine'), (SELECT user_id FROM users WHERE username = 'Serge'), '5', 'En un mot: hétéroclite. La clientèle, la décoration, le cadre... On y mange chinois et indonésien sur des banquettes en bois. ', '12/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Indochine'), (SELECT user_id FROM users WHERE username = 'Ivan'), '5', 'Très ''couleur locale'', ce petit resto où l’on est accueilli comme si on faisait partie de la famille', '12/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Indochine'), (SELECT user_id FROM users WHERE username = 'Brenda'), '4', 'Sympa! pas cher, mais vraiment sympa.', '12/10/2008'),
		((SELECT place_id FROM places WHERE name = 'L''horloge du sud'), (SELECT user_id FROM users WHERE username = 'Fred'), '3', 'Cuisine africaine. Service lent mais sympa et surtout bonne cuisine dépaysante.', '2/10/2008'),
		((SELECT place_id FROM places WHERE name = 'L''horloge du sud'), (SELECT user_id FROM users WHERE username = 'Ivan'), '4', 'Dépaysant, bon, les vins sont super et pas chers (Australien, Afrique du sud...).', '2/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Grenier d''Elvire'), (SELECT user_id FROM users WHERE username = 'Fred'), '2', 'Cuisine sans plus. La terrasse est potable.', '8/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Grenier d''Elvire'), (SELECT user_id FROM users WHERE username = 'Ivan'), '5', 'Meilleur adresse dans le quartier. Surtout pour les salades.', '14/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Grenier d''Elvire'), (SELECT user_id FROM users WHERE username = 'Sarah'), '1', 'Pas bon. ', '21/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Grenier d''Elvire'), (SELECT user_id FROM users WHERE username = 'Serge'), '4', 'Agréable jardin. Bonne ambiance parfois un peu trop bruyant. Belles salades sans oublier les pâtes...carbonara ou poulet fumé et mascarpone...un vrai délice!
', '22/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Grenier d''Elvire'), (SELECT user_id FROM users WHERE username = 'Brenda'), '5', 'Superbe cadre pour déguster les petits plats proposés. Des plats simples mais qui se laissent savourer. Sans parler du moelleux au chocolat... Un service de qualité et une ambiance de fête. Le resto n''est pas très grand donc n''hésitez pas à réserver votre table. Amateurs d''ambiance et de bonne bouffe, ceci est votre adresse!
', '29/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Grain de sel'), (SELECT user_id FROM users WHERE username = 'Brenda'), '3', 'Comme annoncé dans les précédents commentaires, la cuisine était vraiment excellente, les plats raffinés et le rapport qualité-prix imbattable. 
', '2/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Grain de sel'), (SELECT user_id FROM users WHERE username = 'Joelle'), '1', 'Nous avons été réellement déçus par le service (personnel de salle peu disponible et désagréable). En ce qui concerne l’ambiance également, nous nous attendions à un cadre plus cosy, un peu plus accueillant. ', '2/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Grain de sel'), (SELECT user_id FROM users WHERE username = 'Sarah'), '2', 'Impression générale : malgré la qualité des plats, nous ne retournerons pas dans cet endroit à cause du service (dommage!).', '2/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Grain de sel'), (SELECT user_id FROM users WHERE username = 'Serge'), '5', 'Excellent!', '2/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Grain de sel'), (SELECT user_id FROM users WHERE username = 'Fred'), '5', 'Canneloni de saumon et fromage de chèvre, dos de bar au gros sel et épinards en branche, soupe glacé aux framboises le tout servi avec sourire et fraîcheur pour 18 euros ce midi ... Grégory Yarm (le chef-patron) n''a pas fini de m''étonner et c''est tant mieux ! ', '2/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Le Fin de Siècle'), (SELECT user_id FROM users WHERE username = 'Fred'), '5', 'Meilleur adresse du centre. plat de brasserie, simple et bon. Rapport qualité prix imbattable', '2/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Le Fin de Siècle'), (SELECT user_id FROM users WHERE username = 'Joelle'), '2', 'Plein de bruit, service rapide, trop rapide.', '2/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Comme Chez Soi'), (SELECT user_id FROM users WHERE username = 'Boris'), '5', 'Un repas offert au meilleur projet. Ou pas...', '21/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Comme Chez Soi'), (SELECT user_id FROM users WHERE username = 'Fred'), '5', ':-)', '29/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Comme Chez Soi'), (SELECT user_id FROM users WHERE username = 'Sarah'), '5', 'So great!', '23/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Bécasse'), (SELECT user_id FROM users WHERE username = 'Ivan'), '3', 'Une valeur sûre. Ambiance sympa, sans prétention. ', '23/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Bécasse'), (SELECT user_id FROM users WHERE username = 'Serge'), '4', 'Le steak est excellent, le personnel aimable et attentionné. Nous y allons souvent et tjrs avec le même plaisir.', '21/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Bécasse'), (SELECT user_id FROM users WHERE username = 'Sarah'), '3', 'Good.', '29/10/2008'),
		((SELECT place_id FROM places WHERE name = 'La Bastoche'), (SELECT user_id FROM users WHERE username = 'Ivan'), '3', 'Sodexo++ ?', '21/10/2008'),
		((SELECT place_id FROM places WHERE name = 'La Bastoche'), (SELECT user_id FROM users WHERE username = 'Fred'), '2', 'Bon rapport qualité/prix. Pas cher', '22/10/2008'),
		((SELECT place_id FROM places WHERE name = 'La Bastoche'), (SELECT user_id FROM users WHERE username = 'Joelle'), '1', 'Nee', '25/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Au Vieux Bruxelles'), (SELECT user_id FROM users WHERE username = 'Fred'), '4', 'J''adore. ', '2/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Au Vieux Bruxelles'), (SELECT user_id FROM users WHERE username = 'Brenda'), '3', 'Dans la poele, bonne cuisine d''ici.', '2/10/2008'),
		((SELECT place_id FROM places WHERE name = 'Au Vieux Bruxelles'), (SELECT user_id FROM users WHERE username = 'Joelle'), '2', 'Nee', '2/10/2008');
	INSERT INTO tags (place_id, user_id, name) VALUES
		((SELECT place_id FROM places WHERE name = 'Ratabar'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'Ratabar'), (SELECT user_id FROM users WHERE username = 'Brenda'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'Ratabar'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'Ratabar'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Bon marché'),
		((SELECT place_id FROM places WHERE name = 'Ratabar'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Bon marché'),
		((SELECT place_id FROM places WHERE name = 'Ratabar'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Bon marché'),
		((SELECT place_id FROM places WHERE name = 'Ratabar'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'Service au bar'),
		((SELECT place_id FROM places WHERE name = 'Ratabar'), (SELECT user_id FROM users WHERE username = 'Serge'), 'Babyfoot'),
		((SELECT place_id FROM places WHERE name = 'Waff'), (SELECT user_id FROM users WHERE username = 'Brenda'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'Waff'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'Waff'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Waff'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Waff'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Waff'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Waff'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'Service au bar'),
		((SELECT place_id FROM places WHERE name = 'Waff'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Service au bar'),
		((SELECT place_id FROM places WHERE name = 'Waff'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Happy hour'),
		((SELECT place_id FROM places WHERE name = 'Waff'), (SELECT user_id FROM users WHERE username = 'Joelle'), 'Happy hour'),
		((SELECT place_id FROM places WHERE name = 'Waff'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Happy hour'),
		((SELECT place_id FROM places WHERE name = 'Waff'), (SELECT user_id FROM users WHERE username = 'Serge'), 'Happy hour'),
		((SELECT place_id FROM places WHERE name = 'Waff'), (SELECT user_id FROM users WHERE username = 'Boris'), 'WiFi'),
		((SELECT place_id FROM places WHERE name = 'Waff'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'WiFi'),
		((SELECT place_id FROM places WHERE name = 'Waff'), (SELECT user_id FROM users WHERE username = 'Serge'), 'WiFi'),
		((SELECT place_id FROM places WHERE name = 'Tavernier'), (SELECT user_id FROM users WHERE username = 'Serge'), 'Concert'),
		((SELECT place_id FROM places WHERE name = 'Tavernier'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Concert'),
		((SELECT place_id FROM places WHERE name = 'Tavernier'), (SELECT user_id FROM users WHERE username = 'Serge'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Tavernier'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Tavernier'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'Service au bar'),
		((SELECT place_id FROM places WHERE name = 'Tavernier'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Service au bar'),
		((SELECT place_id FROM places WHERE name = 'Belga'), (SELECT user_id FROM users WHERE username = 'Joelle'), 'Concert'),
		((SELECT place_id FROM places WHERE name = 'Belga'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Concert'),
		((SELECT place_id FROM places WHERE name = 'Belga'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'terrasse'),
		((SELECT place_id FROM places WHERE name = 'Belga'), (SELECT user_id FROM users WHERE username = 'Fred'), 'terrasse'),
		((SELECT place_id FROM places WHERE name = 'Belga'), (SELECT user_id FROM users WHERE username = 'Boris'), 'terrasse'),
		((SELECT place_id FROM places WHERE name = 'Belga'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Service au bar'),
		((SELECT place_id FROM places WHERE name = 'Belga'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Service au bar'),
		((SELECT place_id FROM places WHERE name = 'Marché au vin'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Bar à vin'),
		((SELECT place_id FROM places WHERE name = 'Marché au vin'), (SELECT user_id FROM users WHERE username = 'Serge'), 'Bar à vin'),
		((SELECT place_id FROM places WHERE name = 'Marché au vin'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Bar à vin'),
		((SELECT place_id FROM places WHERE name = 'Marché au vin'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'Marché au vin'), (SELECT user_id FROM users WHERE username = 'Joelle'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'Marché au vin'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'Marché au vin'), (SELECT user_id FROM users WHERE username = 'Brenda'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Marché au vin'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Marché au vin'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Service au bar'),
		((SELECT place_id FROM places WHERE name = 'Marché au vin'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Service au bar'),
		((SELECT place_id FROM places WHERE name = 'Delecta'), (SELECT user_id FROM users WHERE username = 'Brenda'), 'Bar à vin'),
		((SELECT place_id FROM places WHERE name = 'Delecta'), (SELECT user_id FROM users WHERE username = 'Serge'), 'Bar à vin'),
		((SELECT place_id FROM places WHERE name = 'Delecta'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Bar à vin'),
		((SELECT place_id FROM places WHERE name = 'Delecta'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Delecta'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Piola'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'Bar à vin'),
		((SELECT place_id FROM places WHERE name = 'Piola'), (SELECT user_id FROM users WHERE username = 'Serge'), 'Bar à vin'),
		((SELECT place_id FROM places WHERE name = 'Piola'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Bar à vin'),
		((SELECT place_id FROM places WHERE name = 'Pantin'), (SELECT user_id FROM users WHERE username = 'Joelle'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'Pantin'), (SELECT user_id FROM users WHERE username = 'Brenda'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'Pantin'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'Pantin'), (SELECT user_id FROM users WHERE username = 'Serge'), 'Echec'),
		((SELECT place_id FROM places WHERE name = 'Pantin'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'Echec'),
		((SELECT place_id FROM places WHERE name = 'Pantin'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Echec'),
		((SELECT place_id FROM places WHERE name = 'Gauguin'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'Gauguin'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'Le Corto'), (SELECT user_id FROM users WHERE username = 'Serge'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'Le Corto'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'Le Corto'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'Le Corto'), (SELECT user_id FROM users WHERE username = 'Joelle'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Le Corto'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'SuperMercado'), (SELECT user_id FROM users WHERE username = 'Brenda'), 'Bar à vin'),
		((SELECT place_id FROM places WHERE name = 'SuperMercado'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Bar à vin'),
		((SELECT place_id FROM places WHERE name = 'SuperMercado'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Bar à vin'),
		((SELECT place_id FROM places WHERE name = 'SuperMercado'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'SuperMercado'), (SELECT user_id FROM users WHERE username = 'Joelle'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'SuperMercado'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'Brasserie L''union'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'Brasserie L''union'), (SELECT user_id FROM users WHERE username = 'Brenda'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'Brasserie L''union'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'Brasserie L''union'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Bon marché'),
		((SELECT place_id FROM places WHERE name = 'Brasserie L''union'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Bon marché'),
		((SELECT place_id FROM places WHERE name = 'Brasserie L''union'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Bon marché'),
		((SELECT place_id FROM places WHERE name = 'Greenwich'), (SELECT user_id FROM users WHERE username = 'Serge'), 'Echec'),
		((SELECT place_id FROM places WHERE name = 'Greenwich'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Echec'),
		((SELECT place_id FROM places WHERE name = 'Greenwich'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Echec'),
		((SELECT place_id FROM places WHERE name = 'Greenwich'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'Greenwich'), (SELECT user_id FROM users WHERE username = 'Joelle'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'Greenwich'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'Greenwich'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Bon marché'),
		((SELECT place_id FROM places WHERE name = 'Greenwich'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Bon marché'),
		((SELECT place_id FROM places WHERE name = 'Greenwich'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Bon marché'),
		((SELECT place_id FROM places WHERE name = 'Michael Collins'), (SELECT user_id FROM users WHERE username = 'Serge'), 'Service au bar'),
		((SELECT place_id FROM places WHERE name = 'Michael Collins'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Service au bar'),
		((SELECT place_id FROM places WHERE name = 'Michael Collins'), (SELECT user_id FROM users WHERE username = 'Joelle'), 'Service au bar'),
		((SELECT place_id FROM places WHERE name = 'Michael Collins'), (SELECT user_id FROM users WHERE username = 'Fred'), 'WiFi'),
		((SELECT place_id FROM places WHERE name = 'Michael Collins'), (SELECT user_id FROM users WHERE username = 'Boris'), 'WiFi'),
		((SELECT place_id FROM places WHERE name = 'Michael Collins'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'WiFi'),
		((SELECT place_id FROM places WHERE name = 'de Valera''s'), (SELECT user_id FROM users WHERE username = 'Fred'), 'WiFi'),
		((SELECT place_id FROM places WHERE name = 'de Valera''s'), (SELECT user_id FROM users WHERE username = 'Brenda'), 'WiFi'),
		((SELECT place_id FROM places WHERE name = 'de Valera''s'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'de Valera''s'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'de Valera''s'), (SELECT user_id FROM users WHERE username = 'Brenda'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'de Valera''s'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'de Valera''s'), (SELECT user_id FROM users WHERE username = 'Joelle'), 'Fumeur'),
		((SELECT place_id FROM places WHERE name = 'de Valera''s'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'de Valera''s'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'de Valera''s'), (SELECT user_id FROM users WHERE username = 'Serge'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Chez Théo Sodexho ULB'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Bon rapport qualité/prix'),
		((SELECT place_id FROM places WHERE name = 'Chez Théo Sodexho ULB'), (SELECT user_id FROM users WHERE username = 'Serge'), 'Bon rapport qualité/prix'),
		((SELECT place_id FROM places WHERE name = 'Chez Théo Sodexho ULB'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Bon marché'),
		((SELECT place_id FROM places WHERE name = 'Chez Théo Sodexho ULB'), (SELECT user_id FROM users WHERE username = 'Serge'), 'Bon marché'),
		((SELECT place_id FROM places WHERE name = 'Chez Théo Sodexho ULB'), (SELECT user_id FROM users WHERE username = 'Joelle'), 'Bon marché'),
		((SELECT place_id FROM places WHERE name = 'Chez Théo Sodexho ULB'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'Bon marché'),
		((SELECT place_id FROM places WHERE name = 'Mirabelle'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Cuisine gastronomique'),
		((SELECT place_id FROM places WHERE name = 'Mirabelle'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'Cuisine gastronomique'),
		((SELECT place_id FROM places WHERE name = 'Mirabelle'), (SELECT user_id FROM users WHERE username = 'Serge'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Mirabelle'), (SELECT user_id FROM users WHERE username = 'Brenda'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Mirabelle'), (SELECT user_id FROM users WHERE username = 'Joelle'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Mano a Mano'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Bon rapport qualité/prix'),
		((SELECT place_id FROM places WHERE name = 'Mano a Mano'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'Bon rapport qualité/prix'),
		((SELECT place_id FROM places WHERE name = 'Mano a Mano'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Mano a Mano'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Mano a Mano'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Mano a Mano'), (SELECT user_id FROM users WHERE username = 'Joelle'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Le belga queen'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Cuisine gastronomique'),
		((SELECT place_id FROM places WHERE name = 'Le belga queen'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Cuisine gastronomique'),
		((SELECT place_id FROM places WHERE name = 'Le belga queen'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Fumoir'),
		((SELECT place_id FROM places WHERE name = 'Le belga queen'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'Fumoir'),
		((SELECT place_id FROM places WHERE name = 'Le belga queen'), (SELECT user_id FROM users WHERE username = 'Serge'), 'Fumoir'),
		((SELECT place_id FROM places WHERE name = 'Indochine'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'Bon rapport qualité/prix'),
		((SELECT place_id FROM places WHERE name = 'Indochine'), (SELECT user_id FROM users WHERE username = 'Brenda'), 'Bon rapport qualité/prix'),
		((SELECT place_id FROM places WHERE name = 'Indochine'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Bon rapport qualité/prix'),
		((SELECT place_id FROM places WHERE name = 'Indochine'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Bon rapport qualité/prix'),
		((SELECT place_id FROM places WHERE name = 'L''horloge du sud'), (SELECT user_id FROM users WHERE username = 'Serge'), 'Bon rapport qualité/prix'),
		((SELECT place_id FROM places WHERE name = 'L''horloge du sud'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Bon rapport qualité/prix'),
		((SELECT place_id FROM places WHERE name = 'L''horloge du sud'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'L''horloge du sud'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'L''horloge du sud'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'L''horloge du sud'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Fumoir'),
		((SELECT place_id FROM places WHERE name = 'L''horloge du sud'), (SELECT user_id FROM users WHERE username = 'Joelle'), 'Fumoir'),
		((SELECT place_id FROM places WHERE name = 'L''horloge du sud'), (SELECT user_id FROM users WHERE username = 'Serge'), 'Fumoir'),
		((SELECT place_id FROM places WHERE name = 'Grenier d''Elvire'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Bon rapport qualité/prix'),
		((SELECT place_id FROM places WHERE name = 'Grenier d''Elvire'), (SELECT user_id FROM users WHERE username = 'Brenda'), 'Bon rapport qualité/prix'),
		((SELECT place_id FROM places WHERE name = 'Grenier d''Elvire'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'Bon rapport qualité/prix'),
		((SELECT place_id FROM places WHERE name = 'Grenier d''Elvire'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Grenier d''Elvire'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Grenier d''Elvire'), (SELECT user_id FROM users WHERE username = 'Joelle'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Grenier d''Elvire'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Fusion'),
		((SELECT place_id FROM places WHERE name = 'Grain de sel'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Bon rapport qualité/prix'),
		((SELECT place_id FROM places WHERE name = 'Grain de sel'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Grain de sel'), (SELECT user_id FROM users WHERE username = 'Serge'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Grain de sel'), (SELECT user_id FROM users WHERE username = 'Joelle'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Grain de sel'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'Fumoir'),
		((SELECT place_id FROM places WHERE name = 'Le Fin de Siècle'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Bon rapport qualité/prix'),
		((SELECT place_id FROM places WHERE name = 'Le Fin de Siècle'), (SELECT user_id FROM users WHERE username = 'Joelle'), 'Bon rapport qualité/prix'),
		((SELECT place_id FROM places WHERE name = 'Le Fin de Siècle'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Bon rapport qualité/prix'),
		((SELECT place_id FROM places WHERE name = 'Le Fin de Siècle'), (SELECT user_id FROM users WHERE username = 'Brenda'), 'Bon rapport qualité/prix'),
		((SELECT place_id FROM places WHERE name = 'Comme Chez Soi'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Bon'),
		((SELECT place_id FROM places WHERE name = 'Comme Chez Soi'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Bon'),
		((SELECT place_id FROM places WHERE name = 'Comme Chez Soi'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Comme Chez Soi'), (SELECT user_id FROM users WHERE username = 'Joelle'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Comme Chez Soi'), (SELECT user_id FROM users WHERE username = 'Serge'), 'Cuisine gastronomique'),
		((SELECT place_id FROM places WHERE name = 'Le café des épices'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Bon marché'),
		((SELECT place_id FROM places WHERE name = 'Le café des épices'), (SELECT user_id FROM users WHERE username = 'Serge'), 'Bon marché'),
		((SELECT place_id FROM places WHERE name = 'Le café des épices'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Terrasse'),
		((SELECT place_id FROM places WHERE name = 'Le café des épices'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'Cuisine brasserie'),
		((SELECT place_id FROM places WHERE name = 'Bécasse'), (SELECT user_id FROM users WHERE username = 'Brenda'), 'Bon marché'),
		((SELECT place_id FROM places WHERE name = 'Bécasse'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Bon marché'),
		((SELECT place_id FROM places WHERE name = 'Bécasse'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Bon marché'),
		((SELECT place_id FROM places WHERE name = 'Bécasse'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Bon marché'),
		((SELECT place_id FROM places WHERE name = 'La Bastoche'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Bon rapport qualité/prix'),
		((SELECT place_id FROM places WHERE name = 'La Bastoche'), (SELECT user_id FROM users WHERE username = 'Fred'), 'Cuisine brasserie'),
		((SELECT place_id FROM places WHERE name = 'La Bastoche'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Cuisine brasserie'),
		((SELECT place_id FROM places WHERE name = 'Au Vieux Bruxelles'), (SELECT user_id FROM users WHERE username = 'Brenda'), 'Bon rapport qualité/prix'),
		((SELECT place_id FROM places WHERE name = 'Au Vieux Bruxelles'), (SELECT user_id FROM users WHERE username = 'Joelle'), 'Bon rapport qualité/prix'),
		((SELECT place_id FROM places WHERE name = 'Au Vieux Bruxelles'), (SELECT user_id FROM users WHERE username = 'Boris'), 'Bon rapport qualité/prix'),
		((SELECT place_id FROM places WHERE name = 'Au Vieux Bruxelles'), (SELECT user_id FROM users WHERE username = 'Serge'), 'Bon'),
		((SELECT place_id FROM places WHERE name = 'Au Vieux Bruxelles'), (SELECT user_id FROM users WHERE username = 'Ivan'), 'Bon'),
		((SELECT place_id FROM places WHERE name = 'Au Vieux Bruxelles'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'Bon'),
		((SELECT place_id FROM places WHERE name = 'Au Vieux Bruxelles'), (SELECT user_id FROM users WHERE username = 'Sarah'), 'Cuisine brasserie');
END
conn = ActiveRecord::Base.connection
conn.execute(sql)
